export const ActionType = {
    FETCH_START: 'FETCH_START',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    FETCH_START_WITH_UNITS: 'FETCH_START_WITH_UNITS',
    FETCH_SUCCESS_WITH_UNITS: 'FETCH_SUCCESS_WITH_UNITS',
    FETCH_ERROR_WITH_UNITS: 'FETCH_ERROR_WITH_UNITS'

  };